# Generated by Django 6.0.7 on 2026-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
